# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aa52bc4091d07fd675cf39d06bfe50ecbf407463e56e5ebccd846a9082c8b8549b73e775de1196303031b6f5d09733db408718ae277477ee182db6b7906ca77

test:
  secret_key_base: 0149e3dc33683cbc9847e41db64f0629ff2882a5de7858134e334924677562d724d20a86f2c1975d8654efd969ead5245aaca43250c8136f604377c247bfcc53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
